name: transcendance
services:
  postgres:
    image: postgres:17.5
    env_file:
      - ./docker/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./docker/entrypoint_db.sh:/usr/local/bin/entrypoint.sh:Z
      - ./certificates/server.crt:/certificates/server.crt:ro
      - ./certificates/server.key:/certificates/server.key
      - ./certificates/rootCA.crt:/certificates/rootCA.crt:ro
      - ./docker/.DB_data/:/var/lib/postgresql/data:rw
      - ./docker/ssl-config.sh:/docker-entrypoint-initdb.d/ssl-config.sh:Z
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/entrypoint.sh"]

  pgAdmin:
    image: dpage/pgadmin4:8
    env_file:
      - ./docker/.env_pgadmin
    ports:
      - 5050:80
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    volumes:
      - ./certificates/rootCA.crt:/home/pgadmin/.postgresql/root.crt:ro
      - ./certificates/client_pgadmin.key:/home/pgadmin/.postgresql/client.key
      - ./certificates/client_pgadmin.crt:/home/pgadmin/.postgresql/client.crt:ro
      - ./docker/entrypoint_ad.sh:/usr/local/bin/entrypoint.sh:Z
    user: root
    entrypoint: ["/bin/sh", "-c", "chown 5050:5050 /home/pgadmin/.postgresql/client.key && /entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgresDB: