import i18n from "../i18n";

const RAW_TO_KEY: Record<string, string> = {
  "Already sent a friend request": "alreadySentFriendRequest",
  "AppID invalide": "invalidAppId",
  "Aucun titre fourni": "noTitleProvided",
  "Blocked": "blocked",
  "Can't block yourself": "cantBlockYourself",
  "Can't send friend request to yourself": "cantFriendYourself",
  "Cannot unblock yourself": "cantUnblockYourself",
  "Comment not found": "commentNotFound",
  "Could not check block": "couldNotCheckBlock",
  "Could not delete comment": "couldNotDeleteComment",
  "Could not find blocked users": "couldNotFindBlockedUsers",
  "Could not find comment": "couldNotFindComment",
  "Could not find conversations": "couldNotFindConversations",
  "Could not save file": "couldNotSaveFile",
  "Could not save vote": "couldNotSaveVote",
  "Could not unblock": "couldNotUnblock",
  "Could not unfriend user": "couldNotUnfriendUser",
  "Couldn't check token validity": "couldNotCheckTokenValidity",
  "Couldn't count match history": "couldNotCountMatchHistory",
  "Couldn't find leaderboard": "couldNotFindLeaderboard",
  "Couldn't find match history": "couldNotFindMatchHistory",
  "Couldn't save comment": "couldNotSaveComment",
  "Email or username already registered": "emailOrUsernameTaken",
  "Erreur lors de la mise à jour des titres": "errorUpdatingTitles",
  "Erreur lors de la récupération des commentaires": "errorFetchingComments",
  "Erreur lors de la récupération des jeux": "errorFetchingGames",
  "Erreur lors du décompte des commentaires": "errorCountingComments",
  "Erreur lors du décompte des jeux": "errorCountingGames",
  "Erreur serveur": "serverErrorGeneric",
  "Failed to accept/reject friend request": "failedAcceptRejectFriendRequest",
  "Failed to block this user": "failedBlockUser",
  "Failed to create user": "failedCreateUser",
  "Failed to generate token": "failedGenerateToken",
  "Failed to logout user": "failedLogout",
  "Failed to save token": "failedSaveToken",
  "Failed to send friend request": "failedSendFriendRequest",
  "Failed to update description": "failedUpdateDescription",
  "File too large": "fileTooLarge",
  "Format d'ID utilisateur en paramètre invalide": "invalidUserIdParamFormat",
  "Format d'ID utilisateur inconnu": "unknownUserIdFormat",
  "Format d'ID utilisateur invalide": "invalidUserIdFormat",
  "Format d'ID utilisateur invalide dans le jeton": "invalidUserIdFormatInToken",
  "Friend request already accepted": "friendRequestAlreadyAccepted",
  "Friend request not found": "friendRequestNotFound",
  "Impossible de mettre à jour la quête": "couldNotUpdateQuest",
  "Invalid JSON body": "invalidJsonBody",
  "Invalid Token": "invalidToken",
  "Invalid comment id": "invalidCommentId",
  "Invalid credential": "invalidCredential",
  "Invalid file type": "invalidFileType",
  "Invalid token": "invalidToken",
  "Invalid token user ID": "invalidTokenUserId",
  "Invalid user ID": "invalidUserId",
  "Invalid userId query parameter": "invalidUserIdQueryParam",
  "Jeu introuvable": "gameNotFound",
  "L'appID doit être un entier valide": "appIdMustBeInteger",
  "Le paramètre 'list' est requis (likes, dislikes, wishlist)": "listParamRequired",
  "Les paramètres 'appID' et 'list' sont requis": "appIdAndListRequired",
  "Login failed": "loginFailed",
  "Missing file": "missingFile",
  "Missing token": "missingToken",
  "No profile picture found": "noProfilePictureFound",
  "Non autorisé": "unauthorized",
  "Not friend with this user": "notFriendWithUser",
  "This user is already blocked": "userAlreadyBlocked",
  "Titre 1 invalide ou non autorisé": "title1Invalid",
  "Titre 2 invalide ou non autorisé": "title2Invalid",
  "Type de liste invalide. Valeurs acceptées: 'likes', 'dislikes', 'wishlist'": "invalidListType",
  "UUID invalide": "invalidUuid",
  "User id missing": "userIdMissing",
  "User not authenticated": "userNotAuthenticated",
  "User not blocked": "userNotBlocked",
  "User not found": "userNotFound",
  "Utilisateur introuvable": "userNotFound",
  "Utilisateur non authentifié": "userNotAuthenticated",
  "Utilisateur non valide ou non authentifié": "invalidOrUnauthenticatedUser",
  "Vote should be 1 or -1": "voteMustBeOneOrMinusOne",
  "failed to find user": "userNotFound",
  "format de requête invalide": "invalidRequestFormat",
  "game not found": "gameNotFound",
  "impossible d'enregistrer le commentaire": "couldNotSaveComment",
  "impossible de récupérer les commentaires": "errorFetchingComments",
  "invalid body": "invalidBody",
  "invalid user id in context": "invalidUserIdInContext",
  "missing search query": "missingSearchQuery",
  "something went wrong": "somethingWentWrong",
  "user id missing from context": "userIdMissingFromContext",
  "user not found": "userNotFound",
};

export function translateBackendError(raw: string | undefined | null): string | undefined {
  if (!raw) return raw ?? undefined;

  const key = RAW_TO_KEY[raw];
	
  if (!key) {
    return raw;
  }

  return i18n.t(`backendErrors.${key}`);
}